# Generated by Django 2.0.4 on 2018-04-25 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=15, verbose_name="Aminal's fspecies")),
                ('time_since_request', models.DurationField()),
                ('symptom', models.CharField(max_length=200, verbose_name='Symptom description')),
                ('first_day_sickness', models.DateTimeField(verbose_name='Time passed from last request')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Farmer's name")),
                ('number_animal_owned', models.IntegerField()),
                ('last_request_date', models.DateTimeField(verbose_name='Last request')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Farmer'),
        ),
    ]
